# default parameters for lane_filter/lane_filter_node

debug : True
predict_frequency: 30.0 # in Hz
mode: SIM
lane_filter_histogram_kf_configuration:
  # ADD PARAMETERS HERE
  mean_d_0: 0
  mean_phi_0: 0
  sigma_d_0: 0.1
  sigma_phi_0: 0.1
  delta_d: 0.02
  delta_phi: 0.1
  d_max: 0.4
  d_min: -0.15
  phi_min: -1.52
  phi_max: 1.52
  cov_v: 0.5
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  min_max: 0.1
  sigma_d_mask: 1.0
  sigma_phi_mask: 2.0
  range_min: 0.2
  range_est: 0.31
  range_max: 0.6
  error_offset: 0.01

edge_bound:
  WHITE_Y:
    min: -0.3
    max: 0.3
  YELLOW_Y:
    min: -0.1
