img_size: [120,160]
top_cutoff: 35

colors:
  RED:
    low_1: [0,140,100]
    high_1: [10,255,255]
    low_2: [165,140,100]
    high_2: [180,255,255]
  WHITE:
    low: [0,0,65]
    high: [180,100,255]
  YELLOW:
    low: [14,106,85]
    high: [31,250,240]
#    low_2: [32,90,75]
#    high_2: [36,210,180]

line_detector_parameters:
  canny_thresholds: [90,230]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1
