img_size: [120,160]
top_cutoff: 40

colors:
  RED:
    low_1: [0,140,100]
    high_1: [10,255,255]
    low_2: [165,140,100]
    high_2: [180,255,255]
  WHITE:
    low: [0,0,100]
    high: [180,100,255]
  YELLOW:
    low: [15, 110, 70]
    high: [35, 255, 245]
#    low: [15,100,90]
#    high: [33,255,245]
#    low_2: [33,90,75]
#    high_2: [36,210,180]

line_detector_parameters:
  canny_thresholds: [85,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1
